send_report:
  name: Отправить отчёт
  fields:
    target:
      name: Цель
      description: "switches | sensors | both"
      example: "both"

test_switches_notify:
  name: Тест уведомлений выключателей

test_sensors_notify:
  name: Тест уведомлений сенсоров
